#!/bin/bash
# This script only works for GAF files generated by GraphAligner >= v1.0.13
# Because it assumes the alignments for each read are in alignment score order
GAF=$1
FNAME=$(basename $GAF)
PREFIX="${FNAME%.gaf}"
awk '!a[$1]++' ${GAF} > ${PREFIX}.filtered.gaf
